// Map FIFA team code → Wikidata country QID + country adjective + ISO.
// Used by image scraper to disambiguate name collisions and rank candidates.

export const COUNTRY_META = {
  ARG: { qid: 'Q414', country: 'Argentina', adjective: 'Argentine', iso: 'ar' },
  AUS: { qid: 'Q408', country: 'Australia', adjective: 'Australian', iso: 'au' },
  AUT: { qid: 'Q40',  country: 'Austria',   adjective: 'Austrian',   iso: 'at' },
  BEL: { qid: 'Q31',  country: 'Belgium',   adjective: 'Belgian',    iso: 'be' },
  BIH: { qid: 'Q225', country: 'Bosnia and Herzegovina', adjective: 'Bosnian', iso: 'ba' },
  BRA: { qid: 'Q155', country: 'Brazil',    adjective: 'Brazilian',  iso: 'br' },
  CAN: { qid: 'Q16',  country: 'Canada',    adjective: 'Canadian',   iso: 'ca' },
  CHE: { qid: 'Q39',  country: 'Switzerland', adjective: 'Swiss',    iso: 'ch' },
  CIV: { qid: 'Q1008', country: "Côte d'Ivoire", adjective: 'Ivorian', iso: 'ci' },
  CMR: { qid: 'Q1009', country: 'Cameroon', adjective: 'Cameroonian', iso: 'cm' },
  COL: { qid: 'Q739', country: 'Colombia',  adjective: 'Colombian',  iso: 'co' },
  CPV: { qid: 'Q1011', country: 'Cape Verde', adjective: 'Cape Verdean', iso: 'cv' },
  CRC: { qid: 'Q800', country: 'Costa Rica', adjective: 'Costa Rican', iso: 'cr' },
  CRO: { qid: 'Q224', country: 'Croatia',   adjective: 'Croatian',   iso: 'hr' },
  CUW: { qid: 'Q25279', country: 'Curaçao', adjective: 'Curaçaoan',  iso: 'cw' },
  CZE: { qid: 'Q213', country: 'Czech Republic', adjective: 'Czech', iso: 'cz' },
  DEN: { qid: 'Q35',  country: 'Denmark',   adjective: 'Danish',     iso: 'dk' },
  DRC: { qid: 'Q974', country: 'DR Congo',  adjective: 'Congolese',  iso: 'cd' },
  ECU: { qid: 'Q736', country: 'Ecuador',   adjective: 'Ecuadorian', iso: 'ec' },
  EGY: { qid: 'Q79',  country: 'Egypt',     adjective: 'Egyptian',   iso: 'eg' },
  ENG: { qid: 'Q21',  country: 'England',   adjective: 'English',    iso: 'gb-eng' },
  ESP: { qid: 'Q29',  country: 'Spain',     adjective: 'Spanish',    iso: 'es' },
  FRA: { qid: 'Q142', country: 'France',    adjective: 'French',     iso: 'fr' },
  GER: { qid: 'Q183', country: 'Germany',   adjective: 'German',     iso: 'de' },
  GHA: { qid: 'Q117', country: 'Ghana',     adjective: 'Ghanaian',   iso: 'gh' },
  HAI: { qid: 'Q790', country: 'Haiti',     adjective: 'Haitian',    iso: 'ht' },
  IRN: { qid: 'Q794', country: 'Iran',      adjective: 'Iranian',    iso: 'ir' },
  ITA: { qid: 'Q38',  country: 'Italy',     adjective: 'Italian',    iso: 'it' },
  JPN: { qid: 'Q17',  country: 'Japan',     adjective: 'Japanese',   iso: 'jp' },
  JOR: { qid: 'Q810', country: 'Jordan',    adjective: 'Jordanian',  iso: 'jo' },
  KOR: { qid: 'Q884', country: 'South Korea', adjective: 'South Korean', iso: 'kr' },
  MAR: { qid: 'Q1028', country: 'Morocco',  adjective: 'Moroccan',   iso: 'ma' },
  MEX: { qid: 'Q96',  country: 'Mexico',    adjective: 'Mexican',    iso: 'mx' },
  NED: { qid: 'Q55',  country: 'Netherlands', adjective: 'Dutch',    iso: 'nl' },
  NOR: { qid: 'Q20',  country: 'Norway',    adjective: 'Norwegian',  iso: 'no' },
  NZL: { qid: 'Q664', country: 'New Zealand', adjective: 'New Zealand', iso: 'nz' },
  PAN: { qid: 'Q804', country: 'Panama',    adjective: 'Panamanian', iso: 'pa' },
  PAR: { qid: 'Q733', country: 'Paraguay',  adjective: 'Paraguayan', iso: 'py' },
  POL: { qid: 'Q36',  country: 'Poland',    adjective: 'Polish',     iso: 'pl' },
  POR: { qid: 'Q45',  country: 'Portugal',  adjective: 'Portuguese', iso: 'pt' },
  QAT: { qid: 'Q846', country: 'Qatar',     adjective: 'Qatari',     iso: 'qa' },
  RSA: { qid: 'Q258', country: 'South Africa', adjective: 'South African', iso: 'za' },
  SAU: { qid: 'Q851', country: 'Saudi Arabia', adjective: 'Saudi',   iso: 'sa' },
  SCO: { qid: 'Q22',  country: 'Scotland',  adjective: 'Scottish',   iso: 'gb-sct' },
  SEN: { qid: 'Q1041', country: 'Senegal',  adjective: 'Senegalese', iso: 'sn' },
  SUI: { qid: 'Q39',  country: 'Switzerland', adjective: 'Swiss',    iso: 'ch' },
  SWE: { qid: 'Q34',  country: 'Sweden',    adjective: 'Swedish',    iso: 'se' },
  TUN: { qid: 'Q948', country: 'Tunisia',   adjective: 'Tunisian',   iso: 'tn' },
  TUR: { qid: 'Q43',  country: 'Türkiye',   adjective: 'Turkish',    iso: 'tr' },
  URU: { qid: 'Q77',  country: 'Uruguay',   adjective: 'Uruguayan',  iso: 'uy' },
  USA: { qid: 'Q30',  country: 'United States', adjective: 'American', iso: 'us' },
  UZB: { qid: 'Q265', country: 'Uzbekistan', adjective: 'Uzbek',     iso: 'uz' },
};

export function countryMeta(teamCode) {
  return COUNTRY_META[teamCode] ?? null;
}
